config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"

  namespace :specs do 
  	get "colors" # 颜色
  	get "fonts" # 字体
  	get "buttons" # 按钮
  	get "icons" # 图标
  	get "images" # 图片
  	get "inputs" # 输入框

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/button.rb
class Button < ApplicationRecord
end

app/models/color.rb
class Color < ApplicationRecord
end

app/models/font.rb
class Font < ApplicationRecord
end

app/models/icon.rb
class Icon < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index 

	end

end

app/controllers/specs_controller.rb
class SpecsController < ApplicationController

	# 颜色
	def colors 
		@colors = Color.all
	end

	# 字体
	def fonts 
		@fonts = Font.all
	end

	# 按钮
	def buttons 
		@buttons = Button.all
	end

	# 图标
	def icons 
		@icons = Icon.all
	end

	# 图片
	def images 
		@images = Image.all
	end

	# 输入框
	def inputs 

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/specs_helper.rb
module SpecsHelper
end

app/views/home/index.html.erb
<h1>御邦医通——UI设计——规范</h1>

<ul class="home-li">

	<li> <%= link_to "色彩", specs_colors_path %> </li>
	<li> <%= link_to "字体", specs_fonts_path %> </li>
	<li> <%= link_to "按钮", specs_buttons_path %> </li>
	<li> <%= link_to "图标", specs_icons_path %> </li>
	<li> <%= link_to "图片", specs_images_path %> </li>
	<li> <%= link_to "输入框", specs_inputs_path %> </li>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UIDesignSpecification</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/specs/buttons.html.erb
<h1>Buttons</h1>

<div class="container">
	<ul>
		<% @buttons.each do |button| %>
			<li>
				<a href="#" class="btn" style="
				  width: <%= button.width %>; 
				  height: <%= button.height %>; 
				  background: <%= button.background %>; 
				  color: <%= button.color %>; 
				  border-radius: <%= button.border_radius %>; 
				  font-size: <%= button.font_size %>; 
				  line-height: <%= button.line_height %>;"
				>
					按钮
				</a>
				<p> 
					width: <%= button.width %>; 
					height: <%= button.height %>; 
					background: <%= button.background %>; 
					color: <%= button.color %>; 
					border-radius: <%= button.border_radius %>; 
					font-size: <%= button.font_size %>; 
					line-height: <%= button.line_height %>; 
				</p>
				<p class="desc-btn">
					<span>适用于：</span>
					<%= button.desc %>
				</p>

			</li>
		<% end -%>
	</ul>
</div>

<%= link_to "返回首页", root_path, { class: "link-a" } %>

app/views/specs/colors.html.erb
<h1>Colors</h1>
<ul class="colors-li">
	<li class="th-li">
		<span>颜色</span>
		<span>rgb颜色值</span>
		<span>说明</span>
	</li>
	
	<% @colors.each do |color| %>
		<li>
			<span>
				<div class="color-div" style="background-color: <%= color.rgb %>;"></div>
			</span>
			<span> <%= color.rgb %> </span>
			<span> <%= color.desc %> </span>
		</li>
	<% end -%>
</ul>
<%= link_to "返回首页", root_path, { class: "link-a" } %>

app/views/specs/fonts.html.erb
<h1>Fonts</h1>
<div>
	<h3> 字体 </h3>
	<p class="font-left"> 系统默认字体 </p>
</div>
<div>
	<h3> 字号 </h3>
	<ul class="colors-li">
		<li class="th-li">
			<span>样式</span>
			<span>字号</span>
			<span>使用场景</span>
		</li>
		
		<% @fonts.each do |font| %>
			<li>
				<span>
					<span style="font-size: <%= font.size %>" > 文字 </span>
				</span>
				<span> <%= font.size %> </span>
				<span> <%= font.desc %> </span>
			</li>
		<% end -%>
	</ul>
</div>
<%= link_to "返回首页", root_path, { class: "link-a" } %>

app/views/specs/icons.html.erb
<h1>Icons</h1>

<ul class="icon-li">
	<% @icons.each do |icon| %>
		<li> 
			<img class="icon" src="/assets/return-a0e88422a45cfddab3b567c383fb6e20061c82ef6a8c9e03300ee370fdbbc474.png" alt="" style="width: <%= icon.width %>px; height: <%= icon.height %>px;" />
			<p> <%= icon.width %> * <%= icon.height %> px </p>
			<p> <%= icon.desc %> </p>		
		</li>
	<% end -%>
</ul>
<%= link_to "返回首页", root_path, { class: "link-a" } %>

app/views/specs/images.html.erb
<h1>Images</h1>

<ul class="icon-li">
	<% @images.each do |image| %>
	<li>
		<div style="width: <%= image.width %>; height: <%= image.height %>; background-color: #e1e1e1;"> </div>
		<p> 描述：<%= image.desc %> </p>
		<p>尺寸：<%= image.width %>*<%= image.height %></p>
	</li>
	<% end %>
	
</ul>
<%= link_to "返回首页", root_path, { class: "link-a" } %>

app/views/specs/inputs.html.erb
<h1>Inputs</h1>